### ISSUE TITLE
When compiling any example, does it produce such an error?!

### ISSUE THREAD

**Issue by todosko** [mathieucarbou/MycilaPZEM004Tv3#1]
K:\Arduino_IDE_1.8.19\portable\sketchbook\libraries\MycilaPZEM004Tv3\examples\Read\Read.ino: In function 'void loop()':
Read:18:10: error: 'class Mycila::PZEM' has no member named 'toJson'
     pzem.toJson(doc.to<JsonObject>());
          ^~~~~~
exit status 1
'class Mycila::PZEM' has no member named 'toJson'

**Comment by mathieucarbou** [comment]
Look at the header and how it runs in CI. If you want Json support, you need:
- to define `-D MYCILA_PZEM_JSON_SUPPORT`
- to add ArduinoJson lib
Json support is optional ;-)

**Comment by todosko** [comment]
This is your "Read.ino" example and it doesn't compile. ArduinoJson lib -  is installed and its examples are compiled good.

**Comment by mathieucarbou** [comment]
> This is your "Read.ino" example and it doesn't compile. ArduinoJson lib - is installed and its examples are compiled good.

It compiles. You just don't know how to compile it ;-)

FYI, this project has some CI setup which verifies at each commit that all samples are compiling.

Like I said, you need to make sure you have the library in place and add the correct macro. 

**Json support is optional.**

**Comment by mathieucarbou** [comment]
https://github.com/mathieucarbou/MycilaPZEM004Tv3/blob/9e5a083542ec0c84cd4c0fb022f08a256beffe53/.github/workflows/ci.yml#L74
