### ISSUE TITLE
Include Mutex error

### ISSUE THREAD

**Issue by intd-in** [mathieucarbou/MycilaPZEM004Tv3#2]
Got following error
Documents\Arduino\libraries\MycilaPZEM004Tv3\src/MycilaPZEM004Tv3.h:9:10: fatal error: mutex: No such file or directory #include <mutex>

Mutexes are typically used for multithreading or multitasking environments, which are not natively supported in most Arduino boards due to their limited resources.
How to use your library with arduinoUno

**Comment by mathieucarbou** [comment]
This library is meant to be used  on multi-core boards such as ESP32. Hence the use of mutexes and async tasks.

If you need Arduino Uno support, feel free to propose a PR. I will be glad to review.
