### ISSUE TITLE
Not able to find my PZEM-004T

### ISSUE THREAD

**Issue by donskytech** [mathieucarbou/MycilaPZEM004Tv3#8]
Hello,
I have tested my PZEM-004T using the other library https://github.com/mandulaj/PZEM-004T-v30 and I was able to retrieve values.

Now, I need to control multiple PZEM-004T using your library and ESP32, but I can't seem to get it to work.
Running the Search.ino, I am getting **"Found 0 devices"**
Do I need to set the address of my PZEM or something?

I am using a NodeMCU ESP32 38 Pins device and my connection is the following

ESP32	PZEM-004T
5V	->	5V
GPIO27 ->	RX
GPIO14 - >	TX
GND ->		GND

Maybe, I am missing something basic? Sorry, can you help please?

**Comment by donskytech** [comment]
After some more checks and trial and error... I changed this line
`pzem.begin(Serial1, 14, 27);`

to this
`pzem.begin(Serial1, 14, 27, MYCILA_PZEM_DEFAULT_ADDRESS, true);`

and the output becomes
```
Found 2 devices
Address: 0x01
Address: 0xF8
```
Is this expected? And why do I get two address when I only have one PZEM-004T connected?

**Comment by mathieucarbou** [comment]
Hello,
There is no difference between the 2 calls: one starts an async task, not the other one. 
So the first one should return some results.
The PZEM have to receive electricity to be working.
`MYCILA_PZEM_DEFAULT_ADDRESS` (0xF8) is the broadcast address
To do a search the search example as it is written will search fro all the address range.

I have at home 2 PZEM on the same Serial1, one at address 0x01 and the other one at address 0x02, I will test.... It is possible that this is something related to the Arduino Core version used also...

**Comment by mathieucarbou** [comment]
@donskytech : Hello, so this is a bug: because scanning 0xF8 will fail on a multi device env. I will fix. I will also issue a new major release with some API changes to match the API of MycilaJSY lib.
